package attendance;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
//jdbc:ucanaccess://C:/TakeAttendance/testdb.accdb
//jdbc:ucanaccess://C:/Users/*****/Documents/IB/CS/IA/Sunday school attendance/testdb.accdb

public class mainScreen extends javax.swing.JFrame {

    /**
     * Creates new form mainScreen
     * @throws java.text.ParseException
     * @throws java.sql.SQLException
     */
    public mainScreen() throws ParseException, SQLException {
        initComponents();
        setLocationRelativeTo(null);
        update();
        select();
        schoolYear = comboyear.getSelectedItem().toString();
        txtyear.setText(schoolYear);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnattendance = new javax.swing.JButton();
        btnstudents = new javax.swing.JButton();
        btnreport = new javax.swing.JButton();
        btncalendar = new javax.swing.JButton();
        btnclasses = new javax.swing.JButton();
        comboyear = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        divider = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnstudentclass = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtyear = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(600, 353));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnattendance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnattendance.setText("Take attendance");
        btnattendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnattendanceActionPerformed(evt);
            }
        });
        jPanel1.add(btnattendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 162, 270, 170));

        btnstudents.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnstudents.setText("Students");
        btnstudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudentsActionPerformed(evt);
            }
        });
        jPanel1.add(btnstudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, 40));

        btnreport.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnreport.setText("Show report");
        btnreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportActionPerformed(evt);
            }
        });
        jPanel1.add(btnreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 252, 180, 50));

        btncalendar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btncalendar.setText("School calendar");
        btncalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalendarActionPerformed(evt);
            }
        });
        jPanel1.add(btncalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 170, 40));

        btnclasses.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnclasses.setText("Classes");
        btnclasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclassesActionPerformed(evt);
            }
        });
        jPanel1.add(btnclasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 160, 40));

        comboyear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboyear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboyearItemStateChanged(evt);
            }
        });
        comboyear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboyearMouseClicked(evt);
            }
        });
        comboyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboyearActionPerformed(evt);
            }
        });
        jPanel1.add(comboyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 122, 120, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("School year:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 125, 90, 20));
        jPanel1.add(divider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Maintenance:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        btnstudentclass.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnstudentclass.setText("Student class");
        btnstudentclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudentclassActionPerformed(evt);
            }
        });
        jPanel1.add(btnstudentclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 192, 180, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Current school year is:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 122, -1, -1));

        txtyear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtyear.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(txtyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 119, 92, 20));

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setText("Select");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 119, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //variables
    static String schoolYear;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    PreparedStatement pst1;
    ResultSet rs1;
    
    private void update() {
        String year;
        comboyear.removeAllItems();
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://C:/TakeAttendance/testdb.accdb");
            pst = con.prepareStatement("select school_year from school_calendar");
            rs = pst.executeQuery();
            while (rs.next()) {
                year = rs.getString("school_year"); //retrieve school year of the record
                comboyear.addItem(year); //add school years into combo box
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(students.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void select() throws ParseException {
        String yr = "1";
        SimpleDateFormat sdformat = new SimpleDateFormat("yyyy-MM-dd");
        String stime = sdformat.format(new Date(System.currentTimeMillis())); //get current time
        Date time = sdformat.parse(stime);
        try {
            con = DriverManager.getConnection("jdbc:ucanaccess://C:/TakeAttendance/testdb.accdb");
            pst = con.prepareStatement("select * from school_calendar");
            rs = pst.executeQuery();
            while(rs.next()){
                Date d1 = rs.getDate("start_date");
                Date d2 = rs.getDate("end_date");
                if(time.compareTo(d1) > 0 && d2.compareTo(time) > 0){
                    yr = rs.getString("school_year");
                }
            }
            if(yr.equals("1")){
                btnattendance.setEnabled(false);
                comboyear.setSelectedIndex(0);
            } else {
                btnattendance.setEnabled(true);
                comboyear.setSelectedItem(yr);
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void test() throws ParseException{
        String d = "2020";
        String date1 = d + "-01-01";
        SimpleDateFormat sdformat = new SimpleDateFormat("yyyy-MM-dd");
        Date y = sdformat.parse(date1);
        Date y2 = sdformat.parse("2019-12-31");
        System.out.println(y2.compareTo(y));
    }
    
    private void btnattendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnattendanceActionPerformed
        try {
            // TODO add your handling code here:
            takeAttendance gui = new takeAttendance();//open take attendance window
            gui.setVisible(true);
            gui.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (SQLException ex) {
            Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnattendanceActionPerformed

    private void btnstudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudentsActionPerformed
        // TODO add your handling code here:
        students gui = new students();        // open students window
        gui.setVisible(true);
        gui.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnstudentsActionPerformed

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
        // TODO add your handling code here:
        showReport gui = new showReport(); //open show report window
        gui.setVisible(true);
        gui.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnreportActionPerformed

    private void btncalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalendarActionPerformed
        // TODO add your handling code here:
        schoolCalendar gui = new schoolCalendar(); // open school calendar window
        gui.setVisible(true);
        gui.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        gui.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    update();
                    select();
                    schoolYear = comboyear.getSelectedItem().toString();
                    txtyear.setText(schoolYear);
                } catch (ParseException ex) {
                    Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_btncalendarActionPerformed

    private void btnclassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclassesActionPerformed
        // TODO add your handling code here:
        classes gui = new classes(); //open classes window
        gui.setVisible(true);
        gui.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnclassesActionPerformed

    private void comboyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboyearActionPerformed
        // TODO add your handling code here:
        /*if(comboyear.getSelectedItem() != null){
            String year = comboyear.getSelectedItem().toString();
            txtyear.setText(year);
            try {
                String yr = "1";
                SimpleDateFormat sdformat = new SimpleDateFormat("yyyy-MM-dd");
                String stime = sdformat.format(new Date(System.currentTimeMillis())); //get current time
                Date time = sdformat.parse(stime);
                con = DriverManager.getConnection("jdbc:ucanaccess://C:/TakeAttendance/testdb.accdb");
                pst = con.prepareStatement("select * from school_calendar");
                rs = pst.executeQuery();
                while(rs.next()){
                    Date d1 = rs.getDate("start_date");
                    Date d2 = rs.getDate("end_date");
                    if(time.compareTo(d1) > 0 && d2.compareTo(time) > 0){
                        yr = rs.getString("school_year");
                    }
                }
                System.out.println(yr);
                if(yr.equals("1")){
                    btnattendance.setEnabled(false);
                } else {
                    btnattendance.setEnabled(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
    }//GEN-LAST:event_comboyearActionPerformed

    private void btnstudentclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudentclassActionPerformed
        // TODO add your handling code here:
        studentClass gui = new studentClass(); //open classes window
        gui.setVisible(true);
        gui.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
    }//GEN-LAST:event_btnstudentclassActionPerformed

    private void comboyearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboyearMouseClicked

    }//GEN-LAST:event_comboyearMouseClicked

    private void comboyearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboyearItemStateChanged

    }//GEN-LAST:event_comboyearItemStateChanged

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        String year = comboyear.getSelectedItem().toString();
        txtyear.setText(year);
        try {
            SimpleDateFormat sdformat = new SimpleDateFormat("yyyy-MM-dd");
            String stime = sdformat.format(new Date(System.currentTimeMillis())); //get current time
            Date time = sdformat.parse(stime);
            con = DriverManager.getConnection("jdbc:ucanaccess://C:/TakeAttendance/testdb.accdb");
            pst = con.prepareStatement("select * from school_calendar where school_year = ?");
            pst.setString(1, year);
            rs = pst.executeQuery();
            while(rs.next()){
                Date d1 = rs.getDate("start_date");
                Date d2 = rs.getDate("end_date");
                if(time.compareTo(d1) > 0 && d2.compareTo(time) > 0){
                    btnattendance.setEnabled(true);
                } else {
                    btnattendance.setEnabled(false);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new mainScreen().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(mainScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnattendance;
    private javax.swing.JButton btncalendar;
    private javax.swing.JButton btnclasses;
    private javax.swing.JButton btnreport;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnstudentclass;
    private javax.swing.JButton btnstudents;
    private javax.swing.JComboBox<String> comboyear;
    private javax.swing.JSeparator divider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtyear;
    // End of variables declaration//GEN-END:variables
}
